name: Publish Icons to NPM RC

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'release-*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Version
        id: extract_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - if: github.event_name == 'push'
        uses: actions/checkout@v4
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - name: Download & Build Icons
        run: npm ci --progress=false && npm run line:build && npm run solid:build && npm run thinline:build && npm run monochrome:build
        env:
          CI_COMMIT_REF_NAME: ${{ steps.extract_version.outputs.VERSION }}
          API_DOWNLOAD_LINE: ${{ secrets.API_DOWNLOAD_LINE }}
          API_DOWNLOAD_SOLID: ${{ secrets.API_DOWNLOAD_SOLID }}
          API_DOWNLOAD_THINLINE: ${{ secrets.API_DOWNLOAD_THINLINE }}
          API_DOWNLOAD_MONOCHROME: ${{ secrets.API_DOWNLOAD_MONOCHROME }}
          RELEASE_DIR: 'release'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Updated Icons
      - name: Publish to CDN
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --no-progress --exclude '.git/*' --exclude 'node_modules/*' --exclude 'build/*' --exclude '.github/*'
        env:
          AWS_S3_BUCKET: 'unicons-iconscout-a5996f0'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEST_DIR: 'release/${{ steps.extract_version.outputs.VERSION }}'
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
